services:
  townhall_backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: townhall_backend
    container_name: townhall_backend
    volumes:
      - ./backend:/backend
      - ./backend/.env:/backend/.env
    ports:
      - 8000:8000
      - 8080:8080
      - 9000:9000
    env_file:
      - ./backend/.env
    restart: always
    depends_on: 
      - database
      - redis

  # frontend
  townhall_frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: townhall_frontend
    container_name: townhall_backend
    volumes:
      - ./frontend:/frontend
      - ./frontend/.env:/frontend/.env
    ports:
      - 3002:3002
      - 3000:300
    env_file:
      ./frontend/.env
    depends_on:
      - townhall_backend

  # database
  database:
    build:
      context: .
      dockerfile: ./backend/postgres/Dockerfile
    image: postgres
    container_name: database
    restart: always
    env_file:
      ./backend/.env
    ports:
      - 5432:5432

  # deployment server -- nginx
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - townhall_backend
    volumes:
      - ./backend/nginx:/backend/nginx
      - ./backend/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf

  # redis
  redis:
    image: redis
    container_name: townhall_redis
    ports:
      - 6379:6379
    restart: always